osx_image: xcode10.2

dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js: "12"

os:
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  chrome: stable # have Travis install chrome stable.

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - yarn

script:

- echo "Deploy windows version to GitHub"
- if [[ "$TRAVIS_BRANCH" == "main" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:win; fi

- echo "Deploy mac version to GitHub"
- if [[ "$TRAVIS_BRANCH" == "main" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:mac; fi
